### ISSUE TITLE
Update Licence 

### ISSUE THREAD

**Issue by iColtz** [kcplayz/discord-embed-pages#1]
This is a complete fork from the following:
https://github.com/iColtz/discord-pages/blob/main/LICENCE

Which has a MIT Licence.
Update your licence before further action is taken.

**Comment by kcplayz** [comment]
Hello, Coltz i Have made this repo and npm package just for fun. I never intended to use this for any other purpose. This is use for the sore purpose of Testing how npm pacages work. I will just remove this repo coz i forgot about this. Sorry for the inconvenience

**Comment by iColtz** [comment]
Don't close the issue without doing anything about it...
